name: Cleanup

env:
  IS_TEMPLATE: ${{ secrets.IS_TEMPLATE }}
  
permissions: write-all

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        if: env.IS_TEMPLATE != 'true'
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: env.IS_TEMPLATE != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and run script
        if: env.IS_TEMPLATE != 'true'
        run: |
          yarn install
          yarn add --dev jsonc-parser
          yarn cleanup "${{ github.event.repository.name }}"
          yarn remove jsonc-parser
          yarn install
        id: script_step
        env:
          IS_TEMPLATE: ${{ secrets.IS_TEMPLATE }}
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        if: env.IS_TEMPLATE != 'true'
        with:
          commit_message: "Cleaned up"
          push_options: --force
